complete -c alita -s d -l delimiter -d 'delimit line by DELIM'
complete -c alita -s r -l regexp -d 'DELIM is a regular expression'
complete -c alita -s c -l count -d 'delimit line COUNT times'
complete -c alita -s m -l margin -d 'join cells by FORMAT'
complete -c alita -s j -l justify -d 'justify cells by SEQUENCE'
complete -c alita -s h -l help -d 'show this help message'
complete -c alita -l version -d 'print the version'
