complete -c csvp -s i -l indexes -d 'select only these indexes'
complete -c csvp -s h -l headers -d 'select only these headers'
complete -c csvp -s t -l tsv -d 'equivalent to -d\'\t\''
complete -c csvp -s d -l delimiter -d 'use DELIM instead of comma for field delimiter'
complete -c csvp -s D -l output-delimiter -d 'use STRING as the output delimiter (default: \t)'
complete -c csvp -l help -d 'display this help text and exit'
complete -c csvp -l version -d 'output version information and exit'
