complete -c 'rant' -s 'e' -l 'expression' -d 'the regex to generate a text (default: '"'"'\w{8}'"'"')'
complete -c 'rant' -s 'c' -l 'count' -d 'print random texts n times (default: 1)'
complete -c 'rant' -s 's' -l 'separator' -d 'print sep between each text (default: '"'"'\n'"'"')'
complete -c 'rant' -l 'help' -d 'display this help and exit'
complete -c 'rant' -l 'version' -d 'display version information and exit'
